export const academyCourses = [
  {
    slug: "tank-gauging",
    code: "JDL–TG01",
    title: "Tank Gauging & Measurement",
    summary: "Build reliable manual gauging habits, from reference points to temperature correction.",
    level: "Foundation",
    duration: "4h 20m",
    lessons: 12,
    learners: 86,
    progress: 68,
    status: "Published",
    accent: "#eeb02b",
  },
  {
    slug: "quantity-verification",
    code: "JDL–QV02",
    title: "Petroleum Quantity Verification",
    summary: "Trace the complete calculation chain from observed volume to verified commercial quantity.",
    level: "Intermediate",
    duration: "6h 10m",
    lessons: 16,
    learners: 54,
    progress: 24,
    status: "Published",
    accent: "#4f8fc7",
  },
  {
    slug: "cargo-operations",
    code: "JDL–CO03",
    title: "Loading & Discharge Operations",
    summary: "Supervise transfers safely and document the checkpoints that protect every stakeholder.",
    level: "Professional",
    duration: "5h 45m",
    lessons: 14,
    learners: 31,
    progress: 0,
    status: "Draft",
    accent: "#76a58b",
  },
] as const;

export const tankModules = [
  { title: "The measurement environment", duration: "24 min", state: "complete" },
  { title: "Equipment checks and field safety", duration: "31 min", state: "complete" },
  { title: "Reference heights & datum plates", duration: "27 min", state: "current" },
  { title: "Taking a manual dip", duration: "38 min", state: "locked" },
  { title: "Temperature & water cuts", duration: "42 min", state: "locked" },
  { title: "Field assessment", duration: "20 min", state: "locked" },
] as const;
