import Link from "next/link";
import { Check, ChevronRight, Play, Timer } from "lucide-react";
import { notFound } from "next/navigation";
import { enrollInAcademyCourse } from "@/app/actions/academy";
import { getCourseForLearner } from "@/lib/academy";
import { getAcademyLearner } from "@/lib/academy-auth";

export const dynamic = "force-dynamic";

export default async function CourseOverview({ params }: { params: Promise<{slug:string}> }) {
  const [{ slug }, learner] = await Promise.all([params, getAcademyLearner()]);
  if (!learner) return null;
  const result = await getCourseForLearner(learner.id, slug);
  if (!result) notFound();
  const lessonCount = result.modules.reduce((sum, module) => sum + module.lessons.length, 0);
  const completeCount = result.modules.reduce((sum, module) => sum + module.lessons.filter((lesson) => lesson.completed).length, 0);
  const percent = lessonCount ? Math.round(completeCount / lessonCount * 100) : 0;
  return <main className="p-5 lg:p-9"><div className="mx-auto max-w-5xl"><Link href="/academy/lms" className="text-sm font-semibold text-ink-faint">← Back to overview</Link><section className="mt-6 overflow-hidden rounded-[28px] bg-navy-950 text-white"><div className="grid lg:grid-cols-[1fr_280px]"><div className="p-7 lg:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-300">{result.course.code} · {result.course.level}</p><h1 className="mt-4 max-w-2xl text-4xl text-white">{result.course.title}</h1><p className="mt-4 max-w-xl text-sm leading-6 text-white/60">{result.course.summary}</p><div className="mt-8 flex gap-5 text-xs text-white/50"><span>{lessonCount} lessons</span><span>{result.course.estimatedMinutes} minutes</span><span>Certificate</span></div>{!result.enrolled ? <form action={enrollInAcademyCourse} className="mt-7"><input type="hidden" name="courseId" value={result.course.id}/><button className="rounded-full bg-gold-500 px-6 py-3 text-sm font-bold text-navy-950">Enrol in this course</button></form> : null}</div><div className="grid place-items-center border-t border-white/10 bg-white/5 p-8 lg:border-l lg:border-t-0"><div className="relative grid h-36 w-36 place-items-center rounded-full" style={{background:`conic-gradient(#eeb02b 0 ${percent}%,rgba(255,255,255,.1) ${percent}%)`}}><div className="grid h-28 w-28 place-items-center rounded-full bg-navy-950 text-center"><span><b className="font-display text-3xl">{percent}%</b><small className="block text-white/40">complete</small></span></div></div></div></div></section>
    {result.enrolled ? <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_290px]"><section><h2 className="mb-4 text-xl">Course route</h2><div className="overflow-hidden rounded-2xl border border-black/5 bg-white">{result.modules.map((module) => <div key={module.id}><div className="bg-[#f7f7f4] px-5 py-3 text-xs font-bold uppercase tracking-wider text-ink-faint">{module.title}</div>{module.lessons.map((lesson, index) => <Link href={`/academy/lms/courses/${result.course.slug}/${lesson.slug}`} key={lesson.id} className="flex items-center gap-4 border-t border-black/5 p-5 hover:bg-[#f8f8f5]"><span className={`grid h-9 w-9 place-items-center rounded-full text-xs font-bold ${lesson.completed?"bg-[#dff2e7] text-[#23734a]":index===0?"bg-gold-500 text-navy-950":"bg-black/5 text-ink-faint"}`}>{lesson.completed?<Check className="h-4 w-4"/>:index+1}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-navy-950">{lesson.title}</b><small className="inline-flex items-center gap-1 text-ink-faint"><Timer className="h-3 w-3"/>{lesson.durationMinutes} min · {lesson.kind}</small></span>{index===0&&!lesson.completed ? <Play className="h-4 w-4 fill-current text-gold-600"/> : <ChevronRight className="h-4 w-4 text-ink-faint"/>}</Link>)}</div>)}</div></section><aside className="space-y-4"><div className="rounded-2xl border border-black/5 bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-gold-600">Course standard</p><p className="mt-4 text-sm leading-6 text-ink-soft">Complete every published lesson and pass the final assessment to earn your credential.</p></div><div className="rounded-2xl bg-gold-500/15 p-6"><p className="text-xs font-bold uppercase tracking-widest text-gold-600">Pass requirement</p><p className="mt-3 text-sm leading-6 text-navy-950">Final score must be at least <b>{result.course.passPercent}%</b>.</p></div></aside></div> : <div className="mt-8 rounded-2xl border border-dashed p-8 text-center text-sm text-ink-soft">Enrol to unlock the curriculum and begin tracking progress.</div>}
  </div></main>;
}
