import Link from "next/link";
import { ArrowLeft, Download } from "lucide-react";
import { getAnalyticsReport } from "@/lib/analytics-reporting";

export const dynamic = "force-dynamic";

export default async function AnalyticsReportsPage() {
  const report = await getAnalyticsReport(14);
  const maximum = Math.max(1, ...report.daily.map((day) => day.count));
  const utilization = report.metrics.todayCapacity ? Math.round((report.metrics.todayUsed / report.metrics.todayCapacity) * 100) : 0;
  return <div className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/analytics" className="inline-flex items-center gap-2 text-xs font-semibold text-ink-faint"><ArrowLeft className="h-3.5 w-3.5" />Analytics access</Link><p className="mt-5 text-[10px] font-bold uppercase tracking-[.2em] text-gold-700">Operations ledger · Last 14 days</p><h1 className="mt-2 font-display text-3xl font-bold text-navy-950">Analytics reporting</h1><p className="mt-2 text-sm text-ink-soft">Subscriber activity, capacity, and source usage at a glance.</p></div><a href="/api/admin/analytics/export" className="inline-flex items-center gap-2 rounded-full bg-navy-950 px-5 py-3 text-sm font-bold text-white"><Download className="h-4 w-4" />Export CSV</a></div>
    <section className="mt-8 grid gap-px overflow-hidden rounded-2xl bg-navy-950 md:grid-cols-4">{[
      ["Active subscribers", report.metrics.activeSubscribers],
      ["Questions · 14d", report.metrics.questions],
      ["New conversations · 14d", report.metrics.conversations],
      ["Today’s capacity", `${utilization}%`],
    ].map(([label, value]) => <div key={label} className="bg-navy-950 p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-widest text-white/45">{label}</p><p className="mt-3 font-display text-3xl font-bold text-gold-400">{value}</p></div>)}</section>
    <section className="mt-6 rounded-2xl border border-black/5 bg-white p-6"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-gold-700">Question throughput</p><h2 className="mt-1 text-xl">Daily subscriber requests</h2></div><p className="text-xs text-ink-faint">Peak {maximum}</p></div><div className="mt-7 grid h-48 grid-cols-14 items-end gap-1.5 border-b border-black/10">{report.daily.map((day) => <div key={day.date} className="group relative flex h-full items-end"><div className="w-full rounded-t bg-gold-500 transition-colors group-hover:bg-navy-800" style={{ height: `${Math.max(day.count ? 8 : 2, (day.count / maximum) * 100)}%` }} /><span className="absolute -bottom-6 left-1/2 -translate-x-1/2 text-[9px] text-ink-faint">{new Date(`${day.date}T00:00:00Z`).getUTCDate()}</span><span className="absolute bottom-full left-1/2 mb-1 hidden -translate-x-1/2 rounded bg-navy-950 px-2 py-1 text-[9px] text-white group-hover:block">{day.count}</span></div>)}</div><p className="mt-8 text-[10px] uppercase tracking-wider text-ink-faint">Calendar day · UTC</p></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]">
      <section className="overflow-hidden rounded-2xl border border-black/5 bg-white"><header className="border-b p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-gold-700">Subscriber ledger</p><h2 className="mt-1 text-xl">Usage and activity</h2></header><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f7f7f4] text-[10px] uppercase tracking-wider text-ink-faint"><tr><th className="p-3">Subscriber</th><th className="p-3">Status</th><th className="p-3 text-right">Questions</th><th className="p-3 text-right">Conversations</th><th className="p-3">Last login</th></tr></thead><tbody className="divide-y">{report.subscribers.map((user) => <tr key={user.id}><td className="p-3 font-semibold text-navy-950">{user.name}<span className="block text-[10px] font-normal text-ink-faint">{user.company ?? "Independent"}</span></td><td className="p-3 text-xs">{user.status}</td><td className="p-3 text-right tabular-nums">{user.questions}</td><td className="p-3 text-right tabular-nums">{user.conversations}</td><td className="p-3 text-xs text-ink-faint">{user.lastLoginAt ? user.lastLoginAt.toLocaleDateString("en-GB") : "Never"}</td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-black/5 bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-gold-700">Source activity</p><h2 className="mt-1 text-xl">Most cited documents</h2>{report.documents.length ? <ol className="mt-5 space-y-3">{report.documents.slice(0, 10).map((document, index) => <li key={document.title} className="flex items-start gap-3 border-b pb-3 last:border-0"><span className="font-mono text-xs text-gold-700">{String(index + 1).padStart(2, "0")}</span><span className="min-w-0 flex-1 text-sm font-semibold text-navy-950">{document.title}</span><span className="rounded-full bg-navy-50 px-2 py-1 text-[10px] font-bold text-navy-800">{document.citations}</span></li>)}</ol> : <p className="mt-5 rounded-xl border border-dashed p-5 text-sm text-ink-faint">Citations will appear after subscribers use indexed sources.</p>}</section>
    </div>
    <p className="mt-5 text-[10px] text-ink-faint">Generated {report.generatedAt.toLocaleString("en-GB", { timeZone: "UTC" })} UTC. Usage counts accepted subscriber questions.</p>
  </div></div>;
}
