import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { getContactSettings } from "@/lib/settings";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms governing access to JDL Core websites and digital services." };

const sections: LegalSection[] = [
  { title: "Acceptance and scope", content: <><p>These terms govern access to JDL Core websites, portals, Analytics, Academy, and related digital services. By using a service, you agree to these terms and any additional written terms that apply to a subscription, inspection engagement, course, or client relationship.</p><p>If you do not agree, do not use the affected service.</p></> },
  { title: "Accounts and access", content: <><p>You must provide accurate information, keep credentials confidential, and notify JDL Core promptly if you suspect unauthorised access. You are responsible for activity performed through your account unless caused by JDL Core&apos;s failure to apply reasonable security.</p><p>Accounts and invitations may not be transferred or shared outside the authorised organisation or user group.</p></> },
  { title: "Acceptable use", content: <><p>You must not misuse the services, interfere with security, access data without permission, upload malicious content, scrape or reverse engineer restricted systems, impersonate another person, infringe intellectual-property rights, or use the platform for unlawful, fraudulent, or harmful activity.</p><p>You must have authority to submit any documents, operational data, personal information, or other content provided through the services.</p></> },
  { title: "Inspection and operational services", content: <><p>Website descriptions and request forms do not by themselves create an inspection engagement. Scope, timing, price, deliverables, assumptions, and reliance rights may be governed by a separate quotation, work order, contract, or report terms.</p><p>Inspection findings reflect the agreed scope, conditions, information, and observations available at the relevant time.</p></> },
  { title: "Analytics and educational content", content: <><p>Analytics outputs and Academy materials are provided for information, decision support, and training. They do not replace professional engineering, legal, financial, safety, or regulatory advice. Important figures and operational decisions should be independently verified by qualified personnel.</p><p>Assessment results and certificates indicate completion under the stated programme requirements and do not guarantee employment, licensing, or regulatory approval.</p></> },
  { title: "Subscriptions, fees, and payments", content: <><p>Prices, billing periods, usage limits, taxes, renewal terms, and refund conditions are those presented during onboarding or in the applicable written agreement. Access may be limited or suspended where payment is overdue or usage exceeds the agreed plan.</p></> },
  { title: "Intellectual property", content: <><p>JDL Core and its licensors retain rights in the website, software, branding, course materials, methodologies, reports, templates, and original content. You may use provided materials only for the purpose and audience authorised by the relevant service or agreement.</p><p>You retain rights in content you lawfully submit, while granting JDL Core the permission needed to host, process, reproduce, and use it to provide and secure the requested service.</p></> },
  { title: "Availability and liability", content: <><p>We aim to provide reliable services but do not promise uninterrupted or error-free access. Maintenance, security events, third-party failures, or circumstances beyond reasonable control may affect availability.</p><p>To the extent permitted by law, liability relating to a paid service will be determined by its applicable written agreement. Nothing in these terms excludes liability that cannot lawfully be excluded.</p></> },
  { title: "Suspension and termination", content: <><p>JDL Core may restrict or terminate access where reasonably necessary to address security, non-payment, unlawful use, material breach, or risk to other users. You may stop using the public website at any time, subject to obligations under any separate agreement.</p></> },
  { title: "Governing law and contact", content: <><p>These terms are governed by the laws of the Republic of Ghana. Disputes should first be raised with JDL Core using the contact details in the footer so the parties can attempt a good-faith resolution.</p><p>We may update these terms as services or legal requirements change. Continued use after an updated version takes effect constitutes acceptance where permitted by law.</p></> },
];

export default async function TermsPage() {
  return <LegalPage title="Terms of Use" description="The rules and responsibilities that apply when accessing JDL Core websites and digital services." updated="27 August 2026" sections={sections} settings={await getContactSettings()} />;
}
