import Link from "next/link";
import { asc, eq, inArray } from "drizzle-orm";
import { ArrowLeft, BookOpen, CircleHelp, Plus, Trash2 } from "lucide-react";
import { notFound } from "next/navigation";
import { createAcademyLesson, createAcademyModule, createAcademyQuizQuestion, deleteAcademyLesson, deleteAcademyModule, deleteAcademyQuizQuestion, moveAcademyLesson, moveAcademyModule, updateAcademyCourse, updateAcademyLesson, updateAcademyModule, updateAcademyQuizQuestion } from "@/app/actions/academy-admin";
import { requireDb } from "@/db";
import { academyCourses, academyLessons, academyModules, academyQuizOptions, academyQuizQuestions } from "@/db/schema";

export const dynamic = "force-dynamic";

export default async function CurriculumEditorPage({ params }: { params: Promise<{ id: string }> }) {
  const courseId = Number((await params).id);
  if (!Number.isInteger(courseId)) notFound();
  const database = requireDb();
  const course = (await database.select().from(academyCourses).where(eq(academyCourses.id, courseId)).limit(1))[0];
  if (!course) notFound();
  const modules = await database.select().from(academyModules).where(eq(academyModules.courseId, courseId)).orderBy(asc(academyModules.position));
  const moduleIds = modules.map((module) => module.id);
  const lessons = moduleIds.length ? await database.select().from(academyLessons).where(inArray(academyLessons.moduleId, moduleIds)).orderBy(asc(academyLessons.position)) : [];
  const quizLessonIds = lessons.filter((lesson) => lesson.kind === "quiz" || lesson.kind === "assessment").map((lesson) => lesson.id);
  const questions = quizLessonIds.length ? await database.select().from(academyQuizQuestions).where(inArray(academyQuizQuestions.lessonId, quizLessonIds)).orderBy(asc(academyQuizQuestions.position)) : [];
  const questionIds = questions.map((question) => question.id);
  const options = questionIds.length ? await database.select().from(academyQuizOptions).where(inArray(academyQuizOptions.questionId, questionIds)).orderBy(asc(academyQuizOptions.position)) : [];

  return <div className="p-5 lg:p-8"><div className="mx-auto max-w-6xl">
    <Link href="/admin/academy/courses" className="inline-flex items-center gap-2 text-sm font-semibold text-ink-faint"><ArrowLeft className="h-4 w-4" />All courses</Link>
    <div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-gold-600">{course.code} · Curriculum editor</p><h1 className="mt-2 text-3xl">{course.title}</h1><p className="mt-2 text-sm text-ink-soft">Build ordered modules, lessons, and scored knowledge checks.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold uppercase ${course.status === "published" ? "bg-green-50 text-green-700" : "bg-gold-500/15 text-gold-600"}`}>{course.status}</span></div>
    <div className="mt-8 grid gap-7 xl:grid-cols-[1fr_330px]">
      <section className="space-y-5">{modules.length ? modules.map((module, moduleIndex) => <article key={module.id} className="overflow-hidden rounded-2xl border border-black/5 bg-white">
        <header className="border-b bg-[#f7f7f4] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-gold-600">Module {moduleIndex + 1}</p><h2 className="mt-1 text-lg">{module.title}</h2>{module.description ? <p className="mt-1 text-xs text-ink-faint">{module.description}</p> : null}</div><MoveControls action={moveAcademyModule} courseId={course.id} itemName="moduleId" itemId={module.id} disableUp={moduleIndex === 0} disableDown={moduleIndex === modules.length - 1} /></div><details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-navy-700">Edit module</summary><form action={updateAcademyModule} className="mt-3 grid gap-3"><input type="hidden" name="courseId" value={course.id} /><input type="hidden" name="moduleId" value={module.id} /><Field label="Module title" name="title" defaultValue={module.title} required /><label><span className="mb-1 block text-xs font-semibold">Description</span><textarea name="description" defaultValue={module.description ?? ""} rows={2} className="w-full rounded-lg border px-3 py-2 text-sm" /></label><div className="flex justify-between"><button className="rounded-lg bg-navy-950 px-4 py-2 text-xs font-bold text-white">Save module</button></div></form><form action={deleteAcademyModule} className="mt-2"><input type="hidden" name="courseId" value={course.id} /><input type="hidden" name="moduleId" value={module.id} /><button className="text-xs font-semibold text-red-700">Delete module and its lessons</button></form></details></header>
        <div className="divide-y">{lessons.filter((lesson) => lesson.moduleId === module.id).map((lesson, lessonIndex) => <div key={lesson.id} className="p-5">
          <div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-navy-100 text-xs font-bold text-navy-800">{lessonIndex + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm text-navy-950">{lesson.title}</b><span className="rounded-full bg-black/5 px-2 py-0.5 text-[10px] uppercase text-ink-faint">{lesson.kind}</span>{!lesson.published ? <span className="rounded-full bg-gold-500/15 px-2 py-0.5 text-[10px] font-bold text-gold-700">hidden</span> : null}</div><p className="mt-1 text-xs text-ink-faint">/{lesson.slug} · {lesson.durationMinutes} min</p></div><MoveControls action={moveAcademyLesson} courseId={course.id} moduleId={module.id} itemName="lessonId" itemId={lesson.id} disableUp={lessonIndex === 0} disableDown={lessonIndex === lessons.filter((item) => item.moduleId === module.id).length - 1} /><form action={deleteAcademyLesson}><input type="hidden" name="courseId" value={course.id} /><input type="hidden" name="lessonId" value={lesson.id} /><button aria-label={`Delete ${lesson.title}`} className="rounded-lg border p-2 text-red-600"><Trash2 className="h-3.5 w-3.5" /></button></form></div>
          <details className="ml-11 mt-3"><summary className="cursor-pointer text-xs font-semibold text-navy-700">Edit lesson</summary><LessonEditForm courseId={course.id} lesson={lesson} /></details>
          {lesson.kind === "quiz" || lesson.kind === "assessment" ? <div className="ml-11 mt-4 rounded-xl border border-dashed p-4"><p className="text-xs font-bold uppercase tracking-wider text-ink-faint">Questions</p>{questions.filter((question) => question.lessonId === lesson.id).map((question, index) => <QuestionEditor key={question.id} courseId={course.id} number={index + 1} question={question} options={options.filter((option) => option.questionId === question.id)} />)}<details className="mt-4"><summary className="cursor-pointer text-xs font-semibold text-navy-700">+ Add question</summary><QuizQuestionForm courseId={course.id} lessonId={lesson.id} /></details></div> : null}
        </div>)}</div>
        <details className="border-t p-5"><summary className="cursor-pointer text-sm font-semibold text-navy-700">+ Add lesson to this module</summary><LessonForm courseId={course.id} moduleId={module.id} /></details>
      </article>) : <div className="rounded-2xl border border-dashed p-10 text-center"><BookOpen className="mx-auto h-8 w-8 text-ink-faint" /><p className="mt-3 text-sm text-ink-soft">Add the first module to begin the curriculum.</p></div>}</section>
      <aside><div className="sticky top-6 space-y-5"><details className="rounded-2xl border border-black/5 bg-white p-5"><summary className="cursor-pointer font-display text-lg font-semibold">Course settings</summary><CourseSettingsForm course={course} /></details><div className="rounded-2xl border border-black/5 bg-white p-5"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-gold-600" /><h2 className="text-lg">Add module</h2></div><form action={createAcademyModule} className="mt-5 space-y-3"><input type="hidden" name="courseId" value={course.id} /><Field label="Module title" name="title" required /><label className="block"><span className="mb-1 block text-xs font-semibold">Description</span><textarea name="description" rows={3} className="w-full rounded-lg border px-3 py-2 text-sm" /></label><button className="btn-gold w-full">Add module</button></form><div className="mt-6 border-t pt-5"><p className="text-xs font-bold uppercase tracking-wider text-ink-faint">Course structure</p><p className="mt-2 text-sm text-ink-soft">{modules.length} modules · {lessons.length} lessons · {questions.length} questions</p></div></div></div></aside>
    </div>
  </div></div>;
}

function CourseSettingsForm({ course }: { course: typeof academyCourses.$inferSelect }) {
  return <form action={updateAcademyCourse} className="mt-4 grid gap-3"><input type="hidden" name="id" value={course.id} /><Field label="Course title" name="title" defaultValue={course.title} required /><Field label="Course code" name="code" defaultValue={course.code} required /><Field label="URL slug" name="slug" defaultValue={course.slug} required /><label><span className="mb-1 block text-xs font-semibold">Level</span><select name="level" defaultValue={course.level} className="h-10 w-full rounded-lg border px-3 text-sm"><option>Foundation</option><option>Intermediate</option><option>Professional</option></select></label><div className="grid grid-cols-2 gap-3"><Field label="Minutes" name="estimatedMinutes" type="number" min="0" defaultValue={course.estimatedMinutes} required /><Field label="Pass mark %" name="passPercent" type="number" min="1" max="100" defaultValue={course.passPercent} required /></div><Field label="Accent colour" name="accent" type="color" defaultValue={course.accent} required /><label><span className="mb-1 block text-xs font-semibold">Summary</span><textarea name="summary" defaultValue={course.summary} required rows={4} className="w-full rounded-lg border px-3 py-2 text-sm" /></label><button className="btn-gold w-full">Save course</button></form>;
}

function LessonEditForm({ courseId, lesson }: { courseId: number; lesson: typeof academyLessons.$inferSelect }) {
  return <form action={updateAcademyLesson} className="mt-3 grid gap-3 sm:grid-cols-2"><input type="hidden" name="courseId" value={courseId} /><input type="hidden" name="moduleId" value={lesson.moduleId} /><input type="hidden" name="lessonId" value={lesson.id} /><Field label="Lesson title" name="title" defaultValue={lesson.title} required /><Field label="URL slug" name="slug" defaultValue={lesson.slug} required /><label><span className="mb-1 block text-xs font-semibold">Type</span><select name="kind" defaultValue={lesson.kind} className="h-10 w-full rounded-lg border px-3 text-sm"><option value="reading">Reading</option><option value="video">Video</option><option value="quiz">Quiz</option><option value="assessment">Assessment</option></select></label><Field label="Minutes" name="durationMinutes" type="number" min="0" defaultValue={lesson.durationMinutes} required /><label className="sm:col-span-2"><span className="mb-1 block text-xs font-semibold">Lesson content</span><textarea name="content" defaultValue={lesson.content ?? ""} rows={6} className="w-full rounded-lg border px-3 py-2 text-sm" /></label><Field label="Video URL" name="videoUrl" type="url" defaultValue={lesson.videoUrl ?? ""} /><Field label="Resource URL" name="resourceUrl" type="url" defaultValue={lesson.resourceUrl ?? ""} /><label><span className="mb-1 block text-xs font-semibold">Visibility</span><select name="published" defaultValue={lesson.published ? "true" : "false"} className="h-10 w-full rounded-lg border px-3 text-sm"><option value="true">Published</option><option value="false">Hidden</option></select></label><button className="justify-self-start rounded-lg bg-navy-950 px-4 py-2 text-xs font-bold text-white sm:self-end">Save lesson</button></form>;
}

function MoveControls({ action, courseId, moduleId, itemName, itemId, disableUp, disableDown }: { action: (formData: FormData) => Promise<void>; courseId: number; moduleId?: number; itemName: "moduleId" | "lessonId"; itemId: number; disableUp: boolean; disableDown: boolean }) {
  return <div className="flex shrink-0 gap-1">{(["up", "down"] as const).map((direction) => <form action={action} key={direction}><input type="hidden" name="courseId" value={courseId} />{moduleId ? <input type="hidden" name="moduleId" value={moduleId} /> : null}<input type="hidden" name={itemName} value={itemId} /><input type="hidden" name="direction" value={direction} /><button disabled={direction === "up" ? disableUp : disableDown} className="grid h-8 w-8 place-items-center rounded-lg border text-xs font-bold disabled:opacity-25" aria-label={`Move ${itemName === "moduleId" ? "module" : "lesson"} ${direction}`}>{direction === "up" ? "↑" : "↓"}</button></form>)}</div>;
}

function QuestionEditor({ courseId, number, question, options }: { courseId: number; number: number; question: typeof academyQuizQuestions.$inferSelect; options: (typeof academyQuizOptions.$inferSelect)[] }) {
  return <div className="mt-3 border-t pt-3"><div className="flex items-start justify-between gap-3"><div><b className="text-sm">{number}. {question.prompt}</b><ul className="mt-2 grid gap-1 sm:grid-cols-2">{options.map((option) => <li key={option.id} className={`text-xs ${option.correct ? "font-semibold text-green-700" : "text-ink-faint"}`}>{option.correct ? "✓" : "○"} {option.label}</li>)}</ul>{question.explanation ? <p className="mt-2 text-xs text-ink-faint">Explanation: {question.explanation}</p> : null}</div><form action={deleteAcademyQuizQuestion}><input type="hidden" name="courseId" value={courseId} /><input type="hidden" name="questionId" value={question.id} /><button className="rounded-lg border p-2 text-red-600" aria-label={`Delete question ${number}`}><Trash2 className="h-3.5 w-3.5" /></button></form></div>
    {options.length === 4 ? <details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-navy-700">Edit question</summary><form action={updateAcademyQuizQuestion} className="mt-3 grid gap-3"><input type="hidden" name="courseId" value={courseId} /><input type="hidden" name="questionId" value={question.id} /><Field label="Question" name="prompt" defaultValue={question.prompt} required />{options.map((option, index) => <div key={option.id}><input type="hidden" name={`option${index}Id`} value={option.id} /><Field label={`Option ${index + 1}`} name={`option${index}`} defaultValue={option.label} required /></div>)}<label><span className="mb-1 block text-xs font-semibold">Correct option</span><select name="correctIndex" defaultValue={Math.max(0, options.findIndex((option) => option.correct))} className="h-10 w-full rounded-lg border px-3 text-sm">{options.map((_, index) => <option key={index} value={index}>Option {index + 1}</option>)}</select></label><Field label="Answer explanation" name="explanation" defaultValue={question.explanation ?? ""} /><button className="justify-self-start rounded-lg bg-navy-950 px-4 py-2 text-xs font-bold text-white">Save question</button></form></details> : <p className="mt-3 text-xs font-semibold text-red-700">This question needs exactly four options. Delete and recreate it.</p>}
  </div>;
}

function LessonForm({ courseId, moduleId }: { courseId: number; moduleId: number }) { return <form action={createAcademyLesson} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="courseId" value={courseId} /><input type="hidden" name="moduleId" value={moduleId} /><Field label="Lesson title" name="title" required /><Field label="URL slug" name="slug" placeholder="manual-dip" required /><label><span className="mb-1 block text-xs font-semibold">Type</span><select name="kind" className="h-10 w-full rounded-lg border px-3 text-sm"><option value="reading">Reading</option><option value="video">Video</option><option value="quiz">Quiz</option><option value="assessment">Assessment</option></select></label><Field label="Minutes" name="durationMinutes" type="number" defaultValue="10" required /><label className="sm:col-span-2"><span className="mb-1 block text-xs font-semibold">Lesson content</span><textarea name="content" rows={5} className="w-full rounded-lg border px-3 py-2 text-sm" /></label><Field label="Video URL (optional)" name="videoUrl" type="url" /><Field label="Resource URL (optional)" name="resourceUrl" type="url" /><button className="btn-gold justify-self-start sm:col-span-2">Create lesson</button></form>; }
function QuizQuestionForm({ courseId, lessonId }: { courseId: number; lessonId: number }) { return <form action={createAcademyQuizQuestion} className="mt-4 grid gap-3"><input type="hidden" name="courseId" value={courseId} /><input type="hidden" name="lessonId" value={lessonId} /><Field label="Question" name="prompt" required />{[0, 1, 2, 3].map((index) => <Field key={index} label={`Option ${index + 1}`} name={`option${index}`} required />)}<label><span className="mb-1 block text-xs font-semibold">Correct option</span><select name="correctIndex" className="h-10 w-full rounded-lg border px-3 text-sm">{[0, 1, 2, 3].map((index) => <option key={index} value={index}>Option {index + 1}</option>)}</select></label><Field label="Answer explanation" name="explanation" /><button className="inline-flex items-center gap-2 justify-self-start rounded-lg bg-navy-950 px-4 py-2 text-xs font-bold text-white"><CircleHelp className="h-3.5 w-3.5" />Add question</button></form>; }
function Field(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const { label, ...rest } = props; return <label className="block"><span className="mb-1 block text-xs font-semibold">{label}</span><input {...rest} className="h-10 w-full rounded-lg border px-3 text-sm" /></label>; }
