import Link from "next/link";
import { ArrowRight, Award, BookOpen, Clock3, Download, Flame, Play } from "lucide-react";
import { getLearnerDashboard } from "@/lib/academy";
import { getAcademyLearner } from "@/lib/academy-auth";

export const dynamic="force-dynamic";

export default async function LearningDashboard(){
  const learner=await getAcademyLearner();
  if(!learner)return null;
  const data=await getLearnerDashboard(learner.id);
  const active=data.courses.find(course=>course.status==="active");
  const totalMinutes=data.courses.reduce((sum,course)=>sum+Math.round(course.estimatedMinutes*course.progress/100),0);
  return <main className="p-5 lg:p-9"><div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold-600">Learner workspace</p><h1 className="mt-2 text-3xl font-bold">Welcome, {learner.name.split(" ")[0]}.</h1><p className="mt-2 text-ink-soft">Continue your learning plan and keep your field competencies current.</p></div><div className="flex gap-3"><Stat icon={Flame} value={`${data.courses.length}`} label="Courses"/><Stat icon={Clock3} value={`${(totalMinutes/60).toFixed(1)} hrs`} label="Progress time"/></div></div>
    {active?<section className="relative overflow-hidden rounded-[28px] bg-navy-950 p-6 text-white shadow-[0_24px_70px_rgba(8,24,38,.18)] lg:p-9"><div className="absolute right-0 top-0 h-full w-1/2 opacity-20" style={{backgroundImage:"repeating-linear-gradient(110deg,transparent 0 28px,rgba(238,176,43,.45) 29px 30px)"}}/><div className="relative max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-300">Continue learning · {active.code}</p><h2 className="mt-3 text-3xl text-white">{active.title}</h2><p className="mt-3 text-sm leading-6 text-white/60">{active.summary}</p><div className="mt-7 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold-500" style={{width:`${active.progress}%`}}/></div><div className="mt-2 flex justify-between text-xs text-white/45"><span>{active.completedCount} of {active.lessonCount} lessons</span><span>{active.progress}% complete</span></div><Link href={`/academy/lms/courses/${active.slug}`} className="mt-7 inline-flex items-center gap-2 rounded-full bg-gold-500 px-6 py-3 text-sm font-bold text-navy-950"><Play className="h-4 w-4 fill-current"/>Continue course</Link></div></section>:<section className="rounded-[28px] border border-dashed border-gold-600/35 bg-white p-8 text-center lg:p-12"><BookOpen className="mx-auto h-9 w-9 text-gold-600"/><h2 className="mt-4 text-2xl">Your learning plan is ready to begin</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-ink-soft">Choose a published course and enrol. Your progress and credentials will appear here.</p><Link href="/academy/courses" className="btn-gold mt-6">Browse course library</Link></section>}
    <div className="mt-8 grid gap-7 xl:grid-cols-[1fr_340px]"><section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl">Your learning plan</h2><Link href="/academy/courses" className="text-sm font-semibold text-navy-700">Browse library →</Link></div>{data.courses.length?<div className="space-y-3">{data.courses.map(course=><Link key={course.slug} href={`/academy/lms/courses/${course.slug}`} className="group flex items-center gap-4 rounded-2xl border border-black/5 bg-white p-4 transition hover:-translate-y-0.5 hover:shadow-lg"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-xl text-xs font-bold" style={{backgroundColor:`${course.accent}22`,color:course.accent}}>{course.code}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-navy-950">{course.title}</b><small className="text-ink-faint">{course.completedCount} of {course.lessonCount} lessons completed</small><span className="mt-2 block h-1 rounded bg-black/5"><span className="block h-full rounded bg-navy-800" style={{width:`${course.progress}%`}}/></span></span><ArrowRight className="h-4 w-4 text-ink-faint transition group-hover:translate-x-1"/></Link>)}</div>:<p className="rounded-2xl border border-dashed p-6 text-sm text-ink-faint">No courses enrolled yet.</p>}
      {data.attempts.length?<div className="mt-8"><h2 className="mb-4 text-xl">Assessment history</h2><div className="overflow-hidden rounded-2xl border border-black/5 bg-white">{data.attempts.map(attempt=><div key={attempt.id} className="flex items-center gap-4 border-b p-4 last:border-0"><span className={`grid h-11 w-11 place-items-center rounded-xl text-sm font-bold ${attempt.passed?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{attempt.scorePercent}%</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{attempt.lessonTitle}</b><small className="text-ink-faint">{attempt.courseTitle} · {attempt.submittedAt.toLocaleDateString("en-GB")}</small></span><span className={`text-xs font-bold ${attempt.passed?"text-green-700":"text-red-700"}`}>{attempt.passed?"Passed":"Retry"}</span></div>)}</div></div>:null}</section>
      <aside id="certificates" className="h-fit rounded-2xl border border-black/5 bg-white p-6"><Award className="h-8 w-8 text-gold-600"/><h2 className="mt-4 text-lg">Certificates</h2>{data.certificates.length?<ul className="mt-4 space-y-4">{data.certificates.map(certificate=><li key={certificate.id} className="border-t pt-4"><b className="block text-sm">{certificate.courseTitle}</b><small className="text-ink-faint">{certificate.certificateNumber}</small><div className="mt-3 flex gap-3"><Link href={`/academy/certificates/${certificate.certificateNumber}`} className="text-xs font-semibold text-navy-700">Verify credential</Link><a href={`/api/academy/certificates/${certificate.certificateNumber}/pdf`} className="inline-flex items-center gap-1 text-xs font-semibold text-gold-600"><Download className="h-3 w-3"/>PDF</a></div></li>)}</ul>:<p className="mt-2 text-sm leading-6 text-ink-soft">Certificates appear here after you complete a course and meet its pass requirement.</p>}</aside></div>
  </div></main>;
}

function Stat({icon:Icon,value,label}:{icon:React.ElementType;value:string;label:string}){return <div className="flex items-center gap-3 rounded-xl border border-black/5 bg-white px-4 py-3"><Icon className="h-5 w-5 text-gold-600"/><span><b className="block text-sm text-navy-950">{value}</b><small className="text-[10px] uppercase tracking-wider text-ink-faint">{label}</small></span></div>}
