import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { getContactSettings } from "@/lib/settings";

export const metadata: Metadata = { title: "Privacy Policy", description: "How JDL Core collects, uses, protects, and manages personal information." };

const sections: LegalSection[] = [
  { title: "Who this policy covers", content: <><p>This policy applies when you use jdlcore.com, contact a JDL Core division, request an inspection, use an authenticated workspace, subscribe to Analytics, or participate in Academy services.</p><p>JDL Core is responsible for determining how personal information submitted through these services is used, unless a separate written agreement states otherwise.</p></> },
  { title: "Information we collect", content: <><p>Depending on your interaction, we may collect names, company and role information, email addresses, telephone numbers, account credentials, service requests, inspection and job records, uploaded documents, comments, payment references, course activity, assessment results, support messages, and Analytics conversations.</p><p>We may also receive basic technical information needed to operate and protect the service, such as IP address, browser information, timestamps, session identifiers, and security logs.</p></> },
  { title: "How we use information", content: <><p>We use information to provide requested services, manage accounts, schedule and document inspections, generate reports and certificates, administer invoices, deliver training, answer Analytics queries, provide support, secure the platform, meet legal obligations, and improve service reliability.</p><p>We do not sell personal information. We do not use personal information for direct marketing without the appropriate permission.</p></> },
  { title: "Legal and operational grounds", content: <><p>We process information where it is necessary to provide a requested service or perform a contract, comply with applicable obligations, protect the platform and its users, pursue a legitimate operational purpose that does not override individual rights, or where consent has been provided.</p><p>Where processing depends on consent, that consent may be withdrawn, subject to any information we must retain for another lawful reason.</p></> },
  { title: "Sharing and service providers", content: <><p>Information may be shared within authorised JDL Core teams and with service providers that support hosting, databases, email, document generation, security, payments, and related operations. Providers should receive only the information reasonably needed for their work and must protect it appropriately.</p><p>We may disclose information where required by law, a regulator, court process, or to protect legal rights, safety, and service integrity.</p></> },
  { title: "Retention and security", content: <><p>We retain information only for as long as reasonably required for the service, contractual records, inspection evidence, learning credentials, dispute handling, security, and applicable legal or regulatory requirements.</p><p>We use reasonable technical and organisational measures such as access controls, authenticated workspaces, role-based permissions, and protected infrastructure. No online system can guarantee absolute security.</p></> },
  { title: "Your rights", content: <><p>Subject to the Data Protection Act, 2012 (Act 843), you may have rights to be informed, access personal data, object to or prevent certain processing, request correction, withdraw consent, avoid solely automated significant decisions, and complain about how information is handled.</p><p>Requests can be sent to the contact email below. We may need to verify identity before acting. You may also contact Ghana&apos;s <a href="https://dataprotection.org.gh/for-individuals/" target="_blank" rel="noreferrer" className="font-semibold text-navy-800 underline underline-offset-4">Data Protection Commission</a>.</p></> },
  { title: "Contact and updates", content: <><p>Questions, access requests, correction requests, or privacy complaints may be sent to the JDL Core information email shown in the footer. This policy may be updated when services, technology, or legal requirements change. Material revisions will be identified by a new last-updated date.</p></> },
];

export default async function PrivacyPage() {
  return <LegalPage title="Privacy Policy" description="How we collect, use, protect, and manage personal information across JDL Core services." updated="27 August 2026" sections={sections} settings={await getContactSettings()} />;
}
